version: '2'
services:
  redis-tcp-proxy:
    env_file:
      - .env.export
    image: demandbase/docker-tcp-proxy
    stdin_open: true
    tty: true
    ports:
    - 23201:6379
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: "true"
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: cluster-type=default
